SGLangDecodeWorker:
  model-path: /model/
  served-model-name: deepseek-ai/DeepSeek-R1
  tp: 16
  dp-size: 16
  enable-dp-attention: true
  trust-remote-code: true
  skip-tokenizer-init: true
  disaggregation-mode: decode
  disaggregation-transfer-backend: nixl
  disaggregation-bootstrap-port: 30001
  dist-init-addr: 10.52.53.75:29500
  nnodes: 2
  node-rank: 0
  enable-deepep-moe: true
  deepep-mode: low_latency
  mem-fraction-static: 0.82
  max-running-requests: 2048
  context-length: 4500
  init-expert-location: /configs/decode_in1000out1000.json
  enable-two-batch-overlap: true
  moe-dense-tp-size: 1
  cuda-graph-bs: 128
  disable-radix-cache: true
  decode-log-interval: 1
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
    envs:
      # missing the SGLANG_HACK_PD_DECODE_NUM_RESERVED_DECODE_TOKENS for now
      SGLANG_HACK_DEEPEP_NEW_MODE: 0
      SGL_ENABLE_JIT_DEEPGEMM: 1