SGLangWorker:
  model-path: /model/
  served-model-name: deepseek-ai/DeepSeek-R1
  tp: 16
  dp-size: 16
  nnodes: 2
  ep-dispatch-algorithm: dynamic
  node-rank: 0
  enable-dp-attention: true
  enable-deepep-moe: true
  deepep-mode: normal
  mem-fraction-static: 0.85
  chunked-prefill-size: 262144
  trust-remote-code: true
  skip-tokenizer-init: true
  disaggregation-mode: prefill
  disaggregation-transfer-backend: nixl
  disaggregation-bootstrap-port: 30001
  max-running-requests: 4096
  max-total-tokens: 131072
  context-length: 8192
  # why am i choosing 1 over the other
  init-expert-location: /configs/prefill_in1000out1000.json
  ep-num-redundant-experts: 32
  enable-two-batch-overlap: true
  moe-dense-tp-size: 1
  disable-radix-cache: true
  dist-init-addr: 10.52.53.73:29500
  port: 30000
  ServiceArgs:
    workers: 1
    resources:
      gpu: 8
    envs:
      MC_TE_METRIC: true
      SGLANG_HACK_DEEPEP_NEW_MODE: 0
      SGL_ENABLE_JIT_DEEPGEMM: 1