apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-shim-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: default
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/preproc"
                    route:
                      cluster: dynamo-frontend
                      host_rewrite_header: x-gateway-destination-endpoint
                      auto_host_rewrite: true
                      timeout: 300s
              http_filters:
              - name: envoy.filters.http.ext_proc
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
                  grpc_service:
                    envoy_grpc:
                      cluster_name: epp-cluster
                  failure_mode_allow: true
              - name: envoy.filters.http.router

      clusters:
      - name: dynamo-frontend
        type: LOGICAL_DNS
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        dns_lookup_family: V4_ONLY
        load_assignment:
          cluster_name: dynamo-frontend
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: placeholder.default.svc.cluster.local  # Overwritten by host_rewrite_header
                    port_value: 8080

      - name: epp-cluster
        type: STRICT_DNS
        connect_timeout: 0.5s
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: epp-cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: dynamo-deepseek-epp.default.svc.cluster.local
                    port_value: 9002
