# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: multi-router
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      serviceAccountName: profile-sla-sa
      containers:
      - name: multi-router
        image: ${DOCKER_IMAGE}
        resources:
          requests:
            cpu: "16"
            memory: "10Gi"
        env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: HF_TOKEN
          - name: NATS_SERVER
            value: nats://${NAMESPACE}-nats:4222
          - name: ETCD_ENDPOINTS
            value: ${NAMESPACE}-etcd:2379
        command: ["python", "/workspace/benchmarks/multi_router/prefix_ratio_benchmark.py"]
        args:
          - --model
          - deepseek-ai/DeepSeek-R1-Distill-Llama-8B
          - --tokenizer
          - deepseek-ai/DeepSeek-R1-Distill-Llama-8B
          - --url
          - http://nginx-optimized-service
          - --output-dir
          - /workspace/multi_router_results
        volumeMounts:
          - name: output-volume
            mountPath: /workspace/multi_router_results
      restartPolicy: Never
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: profiling-pvc
  backoffLimit: 0
