# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: nginx-optimized-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: nginx-optimized
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP