apiVersion: batch/v1
kind: Job
metadata:
  name: profile-sla-disagg
  namespace: ${NAMESPACE}
spec:
  template:
    spec:
      imagePullSecrets:
        - name: nvcrimagepullsecret
      containers:
      - name: profile-sla-disagg
        image: nvcr.io/nvidian/nim-llm-dev/dynamo-base-docker-llm:dep-178.14
        resources:
          requests:
            nvidia.com/gpu: 2
          limits:
            nvidia.com/gpu: 2
        env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: HF_TOKEN
          - name: NATS_SERVER
            value: nats://${NAMESPACE}-nats:4222
          - name: ETCD_ENDPOINTS
            value: ${NAMESPACE}-etcd:2379
        command: ["python", "/workspace/benchmarks/profiler/profile_sla.py"]
        args:
          - --backend
          - vllm_v0
          - --config
          - /workspace/examples/vllm_v0/configs/disagg_planner.yaml
          - --output-dir
          - /workspace/profiling_results
          - --isl
          - "512"
          - --osl
          - "32"
          - --ttft
          - "500"
          - --itl
          - "50"
        volumeMounts:
          - name: output-volume
            mountPath: /workspace/profiling_results
      restartPolicy: Never
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: profiling-pvc
  backoffLimit: 1
