name: Docker Image CI-2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Remove unwanted stuff
        uses: gbraad-actions/remove-unwanted@v1
      - name: free disk
        run: 
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - uses: actions/checkout@v4
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.USERNAME_ALI }}
        password: ${{ secrets.PASSWORD_ALI }}

    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    
    - name: Build the Docker image
      run: |
        chmod +x ./container/build.sh
      
        ./container/build.sh --framework vllm
        docker tag dynamo:latest-vllm  registry.cn-hangzhou.aliyuncs.com/testwydimage/dynamo:latest-vllm
    
        docker push  registry.cn-hangzhou.aliyuncs.com/testwydimage/dynamo:latest-vllm
